package com.mwsx.model;

import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class ViewRewritings {
	// fields
	List<ViewRewriting> viewRewritings;
	// getters
	public List<ViewRewriting> getViewRewritings(){return this.viewRewritings;}
	// setters
	public void setViewRewritings(List<ViewRewriting> _list){this.viewRewritings = _list;}
}