package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class HierarchyTree {
	// fields
	TreeNode classTree;
	TreeNode objectPropertyTree;
	TreeNode dataPropertyTree;
	// getters
	public TreeNode getClassTree(){return this.classTree;}
	public TreeNode getObjectPropertyTree(){return this.objectPropertyTree;}
	public TreeNode getDataPropertyTree(){return this.dataPropertyTree;}
	// setters
	public void setClassTree(TreeNode _classTree){this.classTree = _classTree;}
	public void setObjectPropertyTree(TreeNode _objectPropertyTree){this.objectPropertyTree = _objectPropertyTree;}
	public void setDataPropertyTree(TreeNode _dataPropertyTree){this.dataPropertyTree = _dataPropertyTree;}
}