package com.mwsx.model;

import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class Entity {
	
	// fields
	String entityIRI;
	String entityID;
	String entityPrefixIRI;
	String entityRemainder;
	List<Label> entityLabels;
	String entityType;

	public List<Label> getEntityLabels() {
		return entityLabels;
	}

	public String getEntityType() {
		return entityType;
	}

	public void setEntityType(String entityType) {
		this.entityType = entityType;
	}

	public void setEntityLabels(List<Label> entityLabel) {
		this.entityLabels = entityLabel;
	}

	// getters
	public String getEntityIRI() {
		return this.entityIRI;
	}

	public String getEntityID() {
		return this.entityID;
	}

	public String getEntityPrefixIRI() {
		return entityPrefixIRI;
	}

	public String getEntityRemainder() {
		return entityRemainder;
	}


	// setters
	public void setEntityIRI(String _entityIRI) {
		this.entityIRI = _entityIRI;
	}

	public void setEntityID(String _entityID) {
		this.entityID = _entityID;
	}
	
	public void setEntityPrefixIRI(String entityShortIRI) {
		this.entityPrefixIRI = entityShortIRI;
	}

	public void setEntityRemainder(String entityRemainder) {
		this.entityRemainder = entityRemainder;
	}

}