package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class ViewRewriting {
	// fields
	String query;
	int numResults;
	int time;

	// getters
	public String getQuery() {
		return this.query;
	}

	public int getNumResults() {
		return this.numResults;
	}

	public int getTime() {
		return this.time;
	}

	// setters
	public void setQuery(String _query) {
		this.query = _query;
	}

	public void setNumResults(int _numResults) {
		this.numResults = _numResults;
	}

	public void setTime(int _time) {
		this.time = _time;
	}
}