package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class MappingHead {
	// fields
	String firstArg;
	String secondArg;
	// getters
	public String getFirstArg(){return this.firstArg;}
	public String getSecondArg(){return this.secondArg;}
	// setters
	public void setFirstArg(String _firstArg){this.firstArg = _firstArg;}
	public void setSecondArg(String _secondArg){this.secondArg = _secondArg;}
}