package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class IRI {
	// fields
	String shortIRI;
	String extendedIRI;
	// getters
	public String getShortIRI(){return this.shortIRI;}
	public String getExtendedIRI(){return this.extendedIRI;}
	// setters
	public void setShortIRI(String _shortIRI){this.shortIRI = _shortIRI;}
	public void setExtendedIRI(String _extendedIRI){this.extendedIRI = _extendedIRI;}
	
	public boolean equals(Object o) {
		if (o == null) return false;
		if (o == this) return true;
		if (o.getClass().equals(this.getClass())) {
			return ((IRI)o).getExtendedIRI().equals(this.getExtendedIRI());
		}
		return false;
	}
}