package com.mwsx.model;

import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class Role {
	// fields
	String name;
	List<Permission> permissions;
	
	public List<Permission> getPermissions() {
		return permissions;
	}

	public void setPermissions(List<Permission> permissions) {
		this.permissions = permissions;
	}

	// getters
	public String getName(){return this.name;}

	// setters
	public void setName(String _name){this.name = _name;}
	
	public int hashCode() {
		return this.name.hashCode();
	}

	public boolean equals(Object o) {
		if (o == null)
			return false;
		if (o == this)
			return true;
		if (this.getClass().equals(o.getClass())) {
			Role oo = (Role)o;
			return this.getName().equals(oo.getName());
		}
		return false;
	}
	
	public String toString() {
		String desc = this.getName() + " = ";
		if (this.permissions != null) {
			for (Permission p : this.permissions) {
				desc += p.toString() + ", ";
			}
		}
		return desc.endsWith(", ") ? desc.substring(0, desc.length() - 2) : desc;
	}
	
}