package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class MappingInfo {
	// fields
	Mapping mapping;
	List<DatabaseConnection> mappingDBConnections;
	List<String> mappingTemplates;
	// getters
	public Mapping getMapping(){return this.mapping;}
	public List<DatabaseConnection> getMappingDBConnections(){return this.mappingDBConnections;}
	public List<String> getMappingTemplates(){return this.mappingTemplates;}
	// setters
	public void setMapping(Mapping _mapping){this.mapping = _mapping;}
	public void setMappingDBConnections(List<DatabaseConnection> _mappingDBConnections){this.mappingDBConnections = _mappingDBConnections;}
	public void setMappingTemplates(List<String> _mappingTemplates){this.mappingTemplates = _mappingTemplates;}
}