package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class SPARQLResults {
	// fields
	boolean construct;
	List<String> headTerms;
	List<List<SPARQLResult>> results;
	// getters
	public boolean getConstruct(){return this.construct;}
	public List<String> getHeadTerms(){return this.headTerms;}
	public List<List<SPARQLResult>> getResults(){return this.results;}
	// setters
	public void setConstruct(boolean _construct){this.construct = _construct;}
	public void setHeadTerms(List<String> _headTerms){this.headTerms = _headTerms;}
	public void setResults(List<List<SPARQLResult>> _results){this.results = _results;}
}