package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class OntologyHierarchy {
	// fields
	HierarchyTree hierarchyTree;
	// getters
	public HierarchyTree getHierarchyTree(){return this.hierarchyTree;}
	// setters
	public void setHierarchyTree(HierarchyTree _hierarchyTree){this.hierarchyTree = _hierarchyTree;}
}