package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class MappingBody {
	// fields
	String bodySelect;
	List<SQLView> bodyFrom;
	String bodyWhere;
	// getters
	public String getBodySelect(){return this.bodySelect;}
	public List<SQLView> getBodyFrom(){return this.bodyFrom;}
	public String getBodyWhere(){return this.bodyWhere;}
	// setters
	public void setBodySelect(String _bodySelect){this.bodySelect = _bodySelect;}
	public void setBodyFrom(List<SQLView> _bodyFrom){this.bodyFrom = _bodyFrom;}
	public void setBodyWhere(String _bodyWhere){this.bodyWhere = _bodyWhere;}
}