package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class DataPropertyInfo {
	// fields
	Entity currentEntity;
	IRI iri;
	List<DiagramNode> entityDiagrams;
	List<Label> dataPropertyDescriptions;
	List<Entity> superDataProperties;
	List<Entity> subDataProperties;
	List<Entity> dataPropertyDomain;
	List<Entity> dataPropertyRange;
	List<Entity> dataPropertyIndividuals;
	List<Entity> equivalentDataProperties;
	List<Entity> disjointDataProperties;
	public List<Entity> getDisjointDataProperties() {
		return disjointDataProperties;
	}
	public void setDisjointDataProperties(List<Entity> disjointDataProperties) {
		this.disjointDataProperties = disjointDataProperties;
	}
	Boolean dataPropertyFunctional;
	// getters
	public Entity getCurrentEntity(){return this.currentEntity;}
	public IRI getIri(){return this.iri;}
	public List<DiagramNode> getEntityDiagrams(){return this.entityDiagrams;}
	public List<Label> getDataPropertyDescriptions(){return this.dataPropertyDescriptions;}
	public List<Entity> getSuperDataProperties(){return this.superDataProperties;}
	public List<Entity> getSubDataProperties(){return this.subDataProperties;}
	public List<Entity> getDataPropertyDomain(){return this.dataPropertyDomain;}
	public List<Entity> getDataPropertyRange(){return this.dataPropertyRange;}
	public List<Entity> getDataPropertyIndividuals(){return this.dataPropertyIndividuals;}
	public List<Entity> getEquivalentDataProperties(){return this.equivalentDataProperties;}
	public Boolean getDataPropertyFunctional(){return this.dataPropertyFunctional;}
	// setters
	public void setCurrentEntity(Entity _currentEntity){this.currentEntity = _currentEntity;}
	public void setIri(IRI _iri){this.iri = _iri;}
	public void setEntityDiagrams(List<DiagramNode> _entityDiagrams){this.entityDiagrams = _entityDiagrams;}
	public void setDataPropertyDescriptions(List<Label> _dataPropertyDescriptions){this.dataPropertyDescriptions = _dataPropertyDescriptions;}
	public void setSuperDataProperties(List<Entity> _superDataProperties){this.superDataProperties = _superDataProperties;}
	public void setSubDataProperties(List<Entity> _subDataProperties){this.subDataProperties = _subDataProperties;}
	public void setDataPropertyDomain(List<Entity> _dataPropertyDomain){this.dataPropertyDomain = _dataPropertyDomain;}
	public void setDataPropertyRange(List<Entity> _dataPropertyRange){this.dataPropertyRange = _dataPropertyRange;}
	public void setDataPropertyIndividuals(List<Entity> _dataPropertyIndividuals){this.dataPropertyIndividuals = _dataPropertyIndividuals;}
	public void setEquivalentDataProperties(List<Entity> _equivalentDataProperties){this.equivalentDataProperties = _equivalentDataProperties;}
	public void setDataPropertyFunctional(Boolean _dataPropertyFunctional){this.dataPropertyFunctional = _dataPropertyFunctional;}
}