package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class DiagramNode {
	// fields
	String nodeID;
	String diagramName;
	// getters
	public String getNodeID(){return this.nodeID;}
	public String getDiagramName(){return this.diagramName;}
	// setters
	public void setNodeID(String _nodeID){this.nodeID = _nodeID;}
	public void setDiagramName(String _diagramName){this.diagramName = _diagramName;}
}