package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class FileInfo {
	// fields
	String fileName;
	String fileType;
	String content;
	// getters
	public String getFileName(){return this.fileName;}
	public String getFileType(){return this.fileType;}
	public String getContent(){return this.content;}
	// setters
	public void setFileName(String _fileName){this.fileName = _fileName;}
	public void setFileType(String _fileType){this.fileType = _fileType;}
	public void setContent(String _content){this.content = _content;}
}