package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class InclusionPair {
	// fields
	String leftHandTerm;
	String rightHandTerm;
	// getters
	public String getLeftHandTerm(){return this.leftHandTerm;}
	public String getRightHandTerm(){return this.rightHandTerm;}
	// setters
	public void setLeftHandTerm(String _leftHandTerm){this.leftHandTerm = _leftHandTerm;}
	public void setRightHandTerm(String _rightHandTerm){this.rightHandTerm = _rightHandTerm;}
}