package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class InclusionView {
	// fields
	String sqlViewID;
	List<String> termList;
	// getters
	public String getSqlViewID(){return this.sqlViewID;}
	public List<String> getTermList(){return this.termList;}
	// setters
	public void setSqlViewID(String _sqlViewID){this.sqlViewID = _sqlViewID;}
	public void setTermList(List<String> _termList){this.termList = _termList;}
}