package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class IndividualInfo {
	// fields
	Entity currentEntity;
	IRI iri;
	List<DiagramNode> entityDiagrams;
	List<String> individualDescriptions;
	List<Entity> sameIndividuals;
	List<Entity> differentIndividuals;
	List<Entity> individualTypes;
	// getters
	public Entity getCurrentEntity(){return this.currentEntity;}
	public IRI getIri(){return this.iri;}
	public List<DiagramNode> getEntityDiagrams(){return this.entityDiagrams;}
	public List<String> getIndividualDescriptions(){return this.individualDescriptions;}
	public List<Entity> getSameIndividuals(){return this.sameIndividuals;}
	public List<Entity> getDifferentIndividuals(){return this.differentIndividuals;}
	public List<Entity> getIndividualTypes(){return this.individualTypes;}
	// setters
	public void setCurrentEntity(Entity _currentEntity){this.currentEntity = _currentEntity;}
	public void setIri(IRI _iri){this.iri = _iri;}
	public void setEntityDiagrams(List<DiagramNode> _entityDiagrams){this.entityDiagrams = _entityDiagrams;}
	public void setIndividualDescriptions(List<String> _individualDescriptions){this.individualDescriptions = _individualDescriptions;}
	public void setSameIndividuals(List<Entity> _sameIndividuals){this.sameIndividuals = _sameIndividuals;}
	public void setDifferentIndividuals(List<Entity> _differentIndividuals){this.differentIndividuals = _differentIndividuals;}
	public void setIndividualTypes(List<Entity> _individualTypes){this.individualTypes = _individualTypes;}
}