package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class MapItem {
	// fields
	String mapKey;
	String mapValue;
	// getters
	public String getMapKey(){return this.mapKey;}
	public String getMapValue(){return this.mapValue;}
	// setters
	public void setMapKey(String _mapKey){this.mapKey = _mapKey;}
	public void setMapValue(String _mapValue){this.mapValue = _mapValue;}
}