package com.mwsx.model;

import java.util.LinkedList;
import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class Mapping {
	// fields
	String mappingID;
	String mappingDescription;
	String mappingVersion;
	String fileName;
	String fileType;
	long mappingDate;
	int numAssertions;
	int numViews;
	User mappingOwner;
	int numInclusionDependencies;
	int numKeyDependencies;
	int numDenials;
	List<Prefix> prefixes = new LinkedList<Prefix>();

	// getters
	public String getMappingID() {
		return this.mappingID;
	}

	public String getMappingDescription() {
		return this.mappingDescription;
	}

	public long getMappingDate() {
		return this.mappingDate;
	}

	public int getNumAssertions() {
		return this.numAssertions;
	}

	public int getNumViews() {
		return this.numViews;
	}

	public User getMappingOwner() {
		return this.mappingOwner;
	}

	public int getNumInclusionDependencies() {
		return this.numInclusionDependencies;
	}

	public int getNumKeyDependencies() {
		return this.numKeyDependencies;
	}

	public int getNumDenials() {
		return this.numDenials;
	}

	// setters
	public void setMappingID(String _mappingID) {
		this.mappingID = _mappingID;
	}

	public void setMappingDescription(String _mappingDescription) {
		this.mappingDescription = _mappingDescription;
	}

	public void setMappingDate(long _mappingDate) {
		this.mappingDate = _mappingDate;
	}

	public void setNumAssertions(int _numAssertions) {
		this.numAssertions = _numAssertions;
	}

	public void setNumViews(int _numViews) {
		this.numViews = _numViews;
	}

	public void setMappingOwner(User _mappingOwner) {
		this.mappingOwner = _mappingOwner;
	}

	public void setNumInclusionDependencies(int _numInclusionDependencies) {
		this.numInclusionDependencies = _numInclusionDependencies;
	}

	public void setNumKeyDependencies(int _numKeyDependencies) {
		this.numKeyDependencies = _numKeyDependencies;
	}

	public void setNumDenials(int _numDenials) {
		this.numDenials = _numDenials;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFileType() {
		return fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	public String getMappingVersion() {
		return mappingVersion;
	}

	public void setMappingVersion(String mappingVersion) {
		this.mappingVersion = mappingVersion;
	}

	public List<Prefix> getPrefixes() {
		return prefixes;
	}

	public void setPrefixes(List<Prefix> prefixes) {
		this.prefixes = prefixes;
	}
	
	
	

}