package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class Mappings {
	// fields
	List<Mapping> mappingList;
	
	// getters
	public List<Mapping> getMappingList(){return this.mappingList;}
	
	// setters
	public void setMappingList(List<Mapping> _mappingList){this.mappingList = _mappingList;}
	
}