package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class OBDARunQueryInstance {
	// fields
	String executionId;
	SPARQLQuery sparql;
	
	public String getExecutionId() {
		return executionId;
	}
	public void setExecutionId(String executionId) {
		this.executionId = executionId;
	}
	public SPARQLQuery getSparql() {
		return sparql;
	}
	public void setSparql(SPARQLQuery sparql) {
		this.sparql = sparql;
	}
	
}