package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class OBDAQuery {
	// fields
	SPARQLQuery sparql;
	List<MapItem> options;
	// getters
	public SPARQLQuery getSparql(){return this.sparql;}
	public List<MapItem> getOptions(){return this.options;}
	// setters
	public void setSparql(SPARQLQuery _sparql){this.sparql = _sparql;}
	public void setOptions(List<MapItem> _options){this.options = _options;}
}