package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class Ontology {
	// fields
	String ontologyID;
	String ontologyDescription;
	List<OntologyVersion> ontologyVersions;
	User ontologyOwner;
	long ontologyDate = System.currentTimeMillis();

	// getters
	public String getOntologyID() {
		return this.ontologyID;
	}

	public String getOntologyDescription() {
		return this.ontologyDescription;
	}

	public List<OntologyVersion> getOntologyVersions() {
		return this.ontologyVersions;
	}

	public User getOntologyOwner() {
		return this.ontologyOwner;
	}

	// setters
	public void setOntologyID(String _ontologyID) {
		this.ontologyID = _ontologyID;
	}

	public void setOntologyDescription(String _ontologyDescription) {
		this.ontologyDescription = _ontologyDescription;
	}

	public void setOntologyVersions(List<OntologyVersion> _ontologyVersions) {
		this.ontologyVersions = _ontologyVersions;
	}

	public void setOntologyOwner(User _ontologyOwner) {
		this.ontologyOwner = _ontologyOwner;
	}

	public long getOntologyDate() {
		return ontologyDate;
	}

	public void setOntologyDate(long ontologyDate) {
		this.ontologyDate = ontologyDate;
	}
	
}