package com.mwsx.model;

import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class Ontologies {
	// fields
	List<Ontology> ontologyList;
	// getters
	public List<Ontology> getOntologyList(){return this.ontologyList;}
	// setters
	public void setOntologyList(List<Ontology> _ontologyList){this.ontologyList = _ontologyList;}
}