package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class OntologyMetrics {
	// fields
	List<MapItem> metrics;
	List<MapItem> classAxioms;
	List<MapItem> objectPropertyAxioms;
	List<MapItem> dataPropertyAxioms;
	List<MapItem> individualAxioms;
	List<MapItem> annotationAxioms;
	// getters
	public List<MapItem> getMetrics(){return this.metrics;}
	public List<MapItem> getClassAxioms(){return this.classAxioms;}
	public List<MapItem> getObjectPropertyAxioms(){return this.objectPropertyAxioms;}
	public List<MapItem> getDataPropertyAxioms(){return this.dataPropertyAxioms;}
	public List<MapItem> getIndividualAxioms(){return this.individualAxioms;}
	public List<MapItem> getAnnotationAxioms(){return this.annotationAxioms;}
	// setters
	public void setMetrics(List<MapItem> _metrics){this.metrics = _metrics;}
	public void setClassAxioms(List<MapItem> _classAxioms){this.classAxioms = _classAxioms;}
	public void setObjectPropertyAxioms(List<MapItem> _objectPropertyAxioms){this.objectPropertyAxioms = _objectPropertyAxioms;}
	public void setDataPropertyAxioms(List<MapItem> _dataPropertyAxioms){this.dataPropertyAxioms = _dataPropertyAxioms;}
	public void setIndividualAxioms(List<MapItem> _individualAxioms){this.individualAxioms = _individualAxioms;}
	public void setAnnotationAxioms(List<MapItem> _annotationAxioms){this.annotationAxioms = _annotationAxioms;}
}