package com.mwsx.model;

import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class OntologyRewritings {
	// fields
	List<String> ontologyRewritings;
	// getters

	public List<String> getOntologyRewritings() {
		return ontologyRewritings;
	}

	public void setOntologyRewritings(List<String> ontologyRewritings) {
		this.ontologyRewritings = ontologyRewritings;
	}

	
}