package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class OntologyInfo {
	// fields
	String ontologyIRI;
	List<String> ontologyImports;
	List<Prefix> prefixes;
	List<Label> ontologyDescriptions;
	OntologyMetrics ontologyMetrics;

	// getters
	public String getOntologyIRI() {
		return this.ontologyIRI;
	}

	public List<String> getOntologyImports() {
		return this.ontologyImports;
	}

	public List<Label> getOntologyDescriptions() {
		return this.ontologyDescriptions;
	}

	public OntologyMetrics getOntologyMetrics() {
		return this.ontologyMetrics;
	}

	// setters
	public void setOntologyIRI(String _ontologyIRI) {
		this.ontologyIRI = _ontologyIRI;
	}

	public void setOntologyImports(List<String> _ontologyImports) {
		this.ontologyImports = _ontologyImports;
	}

	public void setOntologyDescriptions(List<Label> _ontologyDescriptions) {
		this.ontologyDescriptions = _ontologyDescriptions;
	}

	public void setOntologyMetrics(OntologyMetrics _ontologyMetrics) {
		this.ontologyMetrics = _ontologyMetrics;
	}

	public List<Prefix> getPrefixes() {
		return prefixes;
	}

	public void setPrefixes(List<Prefix> prefixes) {
		this.prefixes = prefixes;
	}
	
	

}