package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class SPARQLStatus {
	// fields
	String status;
	int percentage;
	int numOntologyRewritings;
	int numHighLevelQueries;
	int numOptimizedQueries;
	int numLowLevelQueries;
	int executionTime;
	int numResults;
	boolean hasError;
	// getters
	public String getStatus(){return this.status;}
	public int getPercentage(){return this.percentage;}
	public int getNumOntologyRewritings(){return this.numOntologyRewritings;}
	public int getNumHighLevelQueries(){return this.numHighLevelQueries;}
	public int getNumOptimizedQueries(){return this.numOptimizedQueries;}
	public int getNumLowLevelQueries(){return this.numLowLevelQueries;}
	public int getExecutionTime(){return this.executionTime;}
	public int getNumResults(){return this.numResults;}
	// setters
	public void setStatus(String _status){this.status = _status;}
	public void setPercentage(int _percentage){this.percentage = _percentage;}
	public void setNumOntologyRewritings(int _numOntologyRewritings){this.numOntologyRewritings = _numOntologyRewritings;}
	public void setNumHighLevelQueries(int _numHighLevelQueries){this.numHighLevelQueries = _numHighLevelQueries;}
	public void setNumOptimizedQueries(int _numOptimizedQueries){this.numOptimizedQueries = _numOptimizedQueries;}
	public void setNumLowLevelQueries(int _numLowLevelQueries){this.numLowLevelQueries = _numLowLevelQueries;}
	public void setExecutionTime(int _executionTime){this.executionTime = _executionTime;}
	public void setNumResults(int _numResults){this.numResults = _numResults;}
	public boolean isHasError() {
		return hasError;
	}
	public void setHasError(boolean hasError) {
		this.hasError = hasError;
	}
	
	
}