package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class SPARQLResult {
	// fields
	String type;
	String shortIRI;
	String value;
	// getters
	public String getType(){return this.type;}
	public String getShortIRI(){return this.shortIRI;}
	public String getValue(){return this.value;}
	// setters
	public void setType(String _type){this.type = _type;}
	public void setShortIRI(String _shortIRI){this.shortIRI = _shortIRI;}
	public void setValue(String _value){this.value = _value;}
}