package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class SQLViews {
	// fields
	List<SQLView> sqlViews;
	// getters
	public List<SQLView> getSqlViews(){return this.sqlViews;}
	// setters
	public void setSqlViews(List<SQLView> _sqlViews){this.sqlViews = _sqlViews;}
}