package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class ViewMappings {
	// fields
	SQLView sqlView;
	List<MappingAssertion> mappingAssertions;
	MappingDependencies mappingDependencies;
	// getters
	public SQLView getSqlView(){return this.sqlView;}
	public List<MappingAssertion> getMappingAssertions(){return this.mappingAssertions;}
	public MappingDependencies getMappingDependencies(){return this.mappingDependencies;}
	// setters
	public void setSqlView(SQLView _sqlView){this.sqlView = _sqlView;}
	public void setMappingAssertions(List<MappingAssertion> _mappingAssertions){this.mappingAssertions = _mappingAssertions;}
	public void setMappingDependencies(MappingDependencies _mappingDependencies){this.mappingDependencies = _mappingDependencies;}
}