package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class TreeNode {
	// fields
	List<TreeNode> children;
	Entity entity;
	// getters
	public List<TreeNode> getChildren(){return this.children;}
	public Entity getEntity(){return this.entity;}
	// setters
	public void setChildren(List<TreeNode> _children){this.children = _children;}
	public void setEntity(Entity _entity){this.entity = _entity;}
}