package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class DatabaseConnection {
	// fields
	String name = "No data source name provided";
	String jdbcURL = "No JDBC Url provided";
	String dbUser = "No JDBC Driver provided";
	String dbDriver = "No JDBC Username provided";
	String dbPassword = "No JDBC Password provided";
	// getters
	public String getJdbcURL(){return this.jdbcURL;}
	public String getDbUser(){return this.dbUser;}
	public String getDbDriver(){return this.dbDriver;}
	public String getDbPassword(){return this.dbPassword;}
	// setters
	public void setJdbcURL(String _jdbcURL){this.jdbcURL = _jdbcURL;}
	public void setDbUser(String _dbUser){this.dbUser = _dbUser;}
	public void setDbDriver(String _dbDriver){this.dbDriver = _dbDriver;}
	public void setDbPassword(String _dbPassword){this.dbPassword = _dbPassword;}
	
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	
}