package com.mwsx.model;

import java.util.List;

import com.mwsx.engine.ChristmasException;
// generated by CodeGeneration.java @ MR (tm)

public class InclusionDependency {
	// fields
	InclusionView includedView;
	InclusionView includingView;
	List<InclusionPair> inclusionMap;

	// getters
	public InclusionView getIncludedView() {
		return this.includedView;
	}

	public InclusionView getIncludingView() {
		return this.includingView;
	}

	public List<InclusionPair> getInclusionMap() {
		return this.inclusionMap;
	}

	// setters
	public void setIncludedView(InclusionView _includedView) {
		this.includedView = _includedView;
	}

	public void setIncludingView(InclusionView _includingView) {
		this.includingView = _includingView;
	}

	public void setInclusionMap(List<InclusionPair> _inclusionMap) {
		this.inclusionMap = _inclusionMap;
	}
}