package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class User {
	// fields
	String name;
	List<Role> roles;
	// getters
	public String getName(){return this.name;}
	public List<Role> getRoles(){return this.roles;}
	// setters
	public void setName(String _name){this.name = _name;}
	public void setRoles(List<Role> _roles){this.roles = _roles;}
	
	public int hashCode() {
		return this.name.hashCode();
	}
	
	public boolean equals(Object o) {
		if (o == null)
			return false;
		if (o == this)
			return true;
		if (this.getClass().equals(o.getClass())) {
			User oo = (User)o;
			return this.getName().equals(oo.getName());
		}
		return false;
	}
	
	public String toString() {
		String desc = this.getName() + " = ";
		if (roles != null) {
			for (Role role : roles) {
				desc += role.getName() + ", ";
			}
		}
		return desc.endsWith(", ") ? desc.substring(0, desc.length() - 2) : desc;
	}
	
	public String toString(String pwd) {
		String desc = this.getName() + " = " + pwd;
		if (roles != null) {
			for (Role role : roles) {
				desc +=  ", " + role.getName();
			}
		}
		return desc;
	}
}