package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class MappingAssertion {
	// fields
	Entity currentEntity;
	IRI iri;
	MappingHead mappingHead;
	MappingBody mappingBody;
	String mappingDescription;
	String id;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	// getters
	public Entity getCurrentEntity(){return this.currentEntity;}
	public IRI getIri(){return this.iri;}
	public MappingHead getMappingHead(){return this.mappingHead;}
	public MappingBody getMappingBody(){return this.mappingBody;}
	public String getMappingDescription(){return this.mappingDescription;}
	// setters
	public void setCurrentEntity(Entity _currentEntity){this.currentEntity = _currentEntity;}
	public void setIri(IRI _iri){this.iri = _iri;}
	public void setMappingHead(MappingHead _mappingHead){this.mappingHead = _mappingHead;}
	public void setMappingBody(MappingBody _mappingBody){this.mappingBody = _mappingBody;}
	public void setMappingDescription(String _mappingDescription){this.mappingDescription = _mappingDescription;}
	
	public boolean equals(Object o) {
		if (o == null) return false;
		if (o == this) return true;
		if (o.getClass().equals(this.getClass())) {
			return ((MappingAssertion)o).getIri().equals(this.getIri());
		}
		return false;
	}
}