package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class SQLView {
	// fields
	String sqlViewID;
	String sqlViewDescription;
	String sqlViewCode;
	// getters
	public String getSqlViewID(){return this.sqlViewID;}
	public String getSqlViewDescription(){return this.sqlViewDescription;}
	public String getSqlViewCode(){return this.sqlViewCode;}
	// setters
	public void setSqlViewID(String _sqlViewID){this.sqlViewID = _sqlViewID;}
	public void setSqlViewDescription(String _sqlViewDescription){this.sqlViewDescription = _sqlViewDescription;}
	public void setSqlViewCode(String _sqlViewCode){this.sqlViewCode = _sqlViewCode;}
}