package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class MappingDependencies {
	// fields
	List<KeyDependency> keyDependencies;
	List<InclusionDependency> inclusionDependencies;
	List<String> denials;
	// getters
	public List<KeyDependency> getKeyDependencies(){return this.keyDependencies;}
	public List<InclusionDependency> getInclusionDependencies(){return this.inclusionDependencies;}
	public List<String> getDenials(){return this.denials;}
	// setters
	public void setKeyDependencies(List<KeyDependency> _keyDependencies){this.keyDependencies = _keyDependencies;}
	public void setInclusionDependencies(List<InclusionDependency> _inclusionDependencies){this.inclusionDependencies = _inclusionDependencies;}
	public void setDenials(List<String> _denials){this.denials = _denials;}
}