package com.mwsx.model;

import java.util.List;

// generated by CodeGeneration.java @ MR (tm)

public class MappingRewritings {
	// fields
	List<String> mappingRewritings;
	// getters

	public List<String> getMappingRewritings() {
		return mappingRewritings;
	}

	public void setMappingRewritings(List<String> mappingRewritings) {
		this.mappingRewritings = mappingRewritings;
	}

	
		
}