package com.mwsx.model;

// generated by CodeGeneration.java @ MR (tm)

public class KeyDependency {
	// fields
	String keyHead;
	String sqlViewID;
	// getters
	public String getKeyHead(){return this.keyHead;}
	public String getSqlViewID(){return this.sqlViewID;}
	// setters
	public void setKeyHead(String _keyHead){this.keyHead = _keyHead;}
	public void setSqlViewID(String _sqlViewID){this.sqlViewID = _sqlViewID;}
}