package com.mwsx.model;

import java.util.List;
// generated by CodeGeneration.java @ MR (tm)

public class ObjectPropertyInfo {
	// fields
	Entity currentEntity;
	IRI iri;
	List<DiagramNode> entityDiagrams;
	List<Entity> superObjectProperties;
	List<Entity> subObjectProperties;
	List<Entity> inverseObjectProperties;
	List<Entity> objectPropertyDomain;
	List<Entity> objectPropertyRange;
	List<Entity> equivalentObjectProperties;
	List<Entity> disjointObjectProperties;
	public List<Entity> getDisjointObjectProperties() {
		return disjointObjectProperties;
	}
	public void setDisjointObjectProperties(List<Entity> disjointObjectProperties) {
		this.disjointObjectProperties = disjointObjectProperties;
	}
	List<String> objectPropertyCharacteristics;
	List<Entity> objectPropertyIndividuals;
	List<Label> objectPropertyDescriptions;
	// getters
	public Entity getCurrentEntity(){return this.currentEntity;}
	public IRI getIri(){return this.iri;}
	public List<DiagramNode> getEntityDiagrams(){return this.entityDiagrams;}
	public List<Entity> getSuperObjectProperties(){return this.superObjectProperties;}
	public List<Entity> getSubObjectProperties(){return this.subObjectProperties;}
	public List<Entity> getInverseObjectProperties(){return this.inverseObjectProperties;}
	public List<Entity> getObjectPropertyDomain(){return this.objectPropertyDomain;}
	public List<Entity> getObjectPropertyRange(){return this.objectPropertyRange;}
	public List<Entity> getEquivalentObjectProperties(){return this.equivalentObjectProperties;}
	public List<String> getObjectPropertyCharacteristics(){return this.objectPropertyCharacteristics;}
	public List<Entity> getObjectPropertyIndividuals(){return this.objectPropertyIndividuals;}
	public List<Label> getObjectPropertyDescriptions(){return this.objectPropertyDescriptions;}
	// setters
	public void setCurrentEntity(Entity _currentEntity){this.currentEntity = _currentEntity;}
	public void setIri(IRI _iri){this.iri = _iri;}
	public void setEntityDiagrams(List<DiagramNode> _entityDiagrams){this.entityDiagrams = _entityDiagrams;}
	public void setSuperObjectProperties(List<Entity> _superObjectProperties){this.superObjectProperties = _superObjectProperties;}
	public void setSubObjectProperties(List<Entity> _subObjectProperties){this.subObjectProperties = _subObjectProperties;}
	public void setInverseObjectProperties(List<Entity> _inverseObjectProperties){this.inverseObjectProperties = _inverseObjectProperties;}
	public void setObjectPropertyDomain(List<Entity> _objectPropertyDomain){this.objectPropertyDomain = _objectPropertyDomain;}
	public void setObjectPropertyRange(List<Entity> _objectPropertyRange){this.objectPropertyRange = _objectPropertyRange;}
	public void setEquivalentObjectProperties(List<Entity> _equivalentObjectProperties){this.equivalentObjectProperties = _equivalentObjectProperties;}
	public void setObjectPropertyCharacteristics(List<String> _objectPropertyCharacteristics){this.objectPropertyCharacteristics = _objectPropertyCharacteristics;}
	public void setObjectPropertyIndividuals(List<Entity> _objectPropertyIndividuals){this.objectPropertyIndividuals = _objectPropertyIndividuals;}
	public void setObjectPropertyDescriptions(List<Label> _objectPropertyDescriptions){this.objectPropertyDescriptions = _objectPropertyDescriptions;}
	
	public Boolean objectPropertyFunctional;
	public Boolean objectPropertyInverseFunctional;
	public Boolean objectPropertyAsymmetric;
	public Boolean objectPropertySymmetric;
	public Boolean objectPropertyTransitive;
	public Boolean objectPropertyReflexive;
	public Boolean objectPropertyIrreflexive;
	
	public Boolean getObjectPropertyFunctional() {
		return objectPropertyFunctional;
	}
	public void setObjectPropertyFunctional(Boolean objectPropertyFunctional) {
		this.objectPropertyFunctional = objectPropertyFunctional;
	}
	public Boolean getObjectPropertyInverseFunctional() {
		return objectPropertyInverseFunctional;
	}
	public void setObjectPropertyInverseFunctional(Boolean objectPropertyInverseFunctional) {
		this.objectPropertyInverseFunctional = objectPropertyInverseFunctional;
	}
	public Boolean getObjectPropertyAsymmetric() {
		return objectPropertyAsymmetric;
	}
	public void setObjectPropertyAsymmetric(Boolean objectPropertyAsymmetric) {
		this.objectPropertyAsymmetric = objectPropertyAsymmetric;
	}
	public Boolean getObjectPropertySymmetric() {
		return objectPropertySymmetric;
	}
	public void setObjectPropertySymmetric(Boolean objectPropertySymmetric) {
		this.objectPropertySymmetric = objectPropertySymmetric;
	}
	public Boolean getObjectPropertyTransitive() {
		return objectPropertyTransitive;
	}
	public void setObjectPropertyTransitive(Boolean objectPropertyTransitive) {
		this.objectPropertyTransitive = objectPropertyTransitive;
	}
	public Boolean getObjectPropertyReflexive() {
		return objectPropertyReflexive;
	}
	public void setObjectPropertyReflexive(Boolean objectPropertyReflexive) {
		this.objectPropertyReflexive = objectPropertyReflexive;
	}
	public Boolean getObjectPropertyIrreflexive() {
		return objectPropertyIrreflexive;
	}
	public void setObjectPropertyIrreflexive(Boolean objectPropertyIrreflexive) {
		this.objectPropertyIrreflexive = objectPropertyIrreflexive;
	}
	
	
	
}